client_id = "b7ae678c6552b0428bb2504aaa6b9991"
name = "cartnova-profit-kit"
application_url = "https://cartnova-profit-kit.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "write_products,read_products,read_orders,read_customers"

[auth]
redirect_urls = ["https://cartnova-profit-kit.vercel.app/auth/callback"]
